In [2]:
import numpy as np
import pandas as pd

### How to create an numpy array?
#### We can create numpy arrays from native python tuples or lists

In [4]:
a=np.array([1,'s'])
a

array(['1', 's'],
      dtype='<U11')

> Note: from above, array can only store same data type, see this integer 1 is converted to string '1'

In [2]:
t=(1,2,3)
a=np.array(t,dtype= 'int')
a

array([1, 2, 3])

In [3]:
list1 = [1,2,3]
a = np.array(list1,dtype='int')
a

array([1, 2, 3])

In [4]:
a.dtype

dtype('int32')

In [5]:
a = np.array(list1,dtype= 'float32') #32 is just the bits of the data, can also be 64 bits, does not matter that much
a

array([ 1.,  2.,  3.], dtype=float32)

In [6]:
list2 = [4.2,5.1,6.3]
b = np.array([list1,list2])  #2x2 array
b #force int-> float for elements in list 1

array([[ 1. ,  2. ,  3. ],
       [ 4.2,  5.1,  6.3]])

In [7]:
b.dtype

dtype('float64')

In [18]:
c = np.array( [ [1,2], [3,4] ], dtype=complex ) #complex number
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

### Shape of array

In [19]:
c.shape

(2, 2)

In [11]:
a = np.array([[4,2,1]])
print (a)
print(a.shape)  #--2D array

[[4 2 1]]
(1, 3)


In [17]:
a2=np.array([4,2,1])
print(a2)
print(a2.shape) #--1D array, similar to a list
#Note the difference from above(above is 2D array)!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[4 2 1]
(3,)


In [13]:
b=np.array([[3,2,1],[6,5,4]])
print (b)
print (b.shape)

[[3 2 1]
 [6 5 4]]
(2, 3)


### Axis of arrays 
> see shape of arrays, if shape is (2,3), then 2--> axis 0 (2 elements along axis 0), 3--> axis 1 (3 elements along axis 1)

### Create Special Arrays

In [8]:
np.zeros([2,2])

array([[ 0.,  0.],
       [ 0.,  0.]])

In [9]:
np.ones([2,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
np.empty([2,3]) 

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.eye(5) #Identity Matrix I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.arange(2,10,2) #array range [start,end) 

array([2, 4, 6, 8])

In [10]:
np.linspace(0,10,3) # 3 numbers from 0 to 10

array([  0.,   5.,  10.])