In [3]:
import numpy as np

## Saving array in binary format (.npy)- .save() and load array- .load()

In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
np.save('array_a',a) #you will find a separate file being saved in current folder

In [10]:
b=np.load('array_a.npy')
b

array([1, 2, 3, 4, 5])

## Saving multiple arrays into a zip file- .savez() and load separately

In [12]:
b = np.array([[1,2,3],[4,5,6]])
c=np.array ([3,2,1])

In [13]:
np.savez('two_arrays.npz',x=b,y=c)

In [14]:
np.load('two_arrays.npz')['x']

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.load('two_arrays.npz')['y']

array([3, 2, 1])

## Saving and loading into text(csv) files- .savetxt()

In [16]:
np.savetxt('array_text.txt',b,delimiter=',') # save as csv file

In [17]:
np.loadtxt('array_text.txt',delimiter=',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])