In [1]:
# 这一小节我们来讲 np array 的选取，我们先来看看一维array的选取，然后我们进行二维以及多维 array的选取

# NOTE: VIP difference detween Numpy array slicing and Python list slicing
- Numpy array reassign elements in sliced array, then original array changes;  
- (BUT NOT FOR BOOLEAN INDEXING, Boolean Indexing is the same as Python slicing, change of child array will not effect parent array, **NOT  LINKED**) -- see the note at the end
- Python list reassign elements in sliced array, original array not change

## One-dimensional arrays.

In [24]:
# Python List slicing-- create a copy
a=[0,1,2,3]
b=a[1:3]
b[0]=99 #modify b, part of b's value change
print (a) #same as original

[0, 1, 2, 3]


In [1]:
a=[0,1,2,3]
b=a #create a view!
b[0]=99
print (a) # a changes 

[99, 1, 2, 3]


In [3]:
# np array slicing compared to python list, diff-- create a view!
import numpy as np
a = np.arange(10)**2
print (a)
b=a[1:3]
b[0]=99
print (a) #changed

[ 0  1  4  9 16 25 36 49 64 81]
[ 0 99  4  9 16 25 36 49 64 81]


In [25]:
# np array slicing compared to python list, diff-- create a view!
import numpy as np
a = np.arange(10)**2
print (a)
b=a[1:4]
c=b[1:3]
c[0]=99
print (a) #changed

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  1 99  9 16 25 36 49 64 81]


In [2]:
# if use b=a, not b=a[:], then create a view, not a copy, this is the same as python list!
import numpy as np 
a = np.arange(10)**2
print (a)
b=a
b[0]=99
print (a) #changed

[ 0  1  4  9 16 25 36 49 64 81]
[99  1  4  9 16 25 36 49 64 81]


In [11]:
#Conclusion:
# 注意： 当我们选取部分 np array 的时候，我们创建了一个view。
# 换句话说，我们没有copy以前的值，而是直接改了原来的 array 


In [19]:
# 如果不想对原来的 array 进行修改，我们可以把选取的部分 copy 出来
a=np.array([1,2,3,4,5,6])
b = a[0:5].copy()
b[0] = 500
print (a) #using copy(), b changes, but 'a' not changed

[1 2 3 4 5 6]


## Multidimensional arrays.

In [10]:
# create multidimensional arrays by function
def f(x,y):
    return 4 * x + y
b = np.fromfunction(f,(3,2),dtype=int)
b

# derive from locations of the matrix
#[[00],[01],[10],[11],[20],[21]]
# position=(0,0)--> value=4*0+0=0
# position=(0,1)--> value=4*0+1=1
# ......

array([[0, 1],
       [4, 5],
       [8, 9]])

In [14]:
b[1]

array([4, 5])

In [15]:
b[1][0]

4

In [15]:
b[1,0]

4

In [16]:
b[:, 1]

array([1, 5, 9])

In [24]:
c = np.zeros ([6,5])
c

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [25]:
Numberofcolumn = c.shape[1]
Numberofcolumn

5

In [26]:
for i in range(Numberofcolumn):
    c[i] = i
    print(c[i])

[ 0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.]
[ 2.  2.  2.  2.  2.]
[ 3.  3.  3.  3.  3.]
[ 4.  4.  4.  4.  4.]


In [30]:
print(c)

[[ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.]
 [ 0.  0.  0.  0.  0.]]


## Boolean Indexing

In [5]:
week_days=np.array(['Monday','Tuesday','Wednesday','Thursday','Friday'])

In [6]:
work_time=np.round(np.random.randn(5,5)+8.0, 2) #generate random number for elements with mean=8, 2 decimal places

In [7]:
work_time

array([[ 7.88,  6.55,  6.53,  8.73,  6.73],
       [ 7.59,  8.67,  9.58,  6.16,  7.99],
       [ 9.85,  6.31,  8.17,  9.92,  6.59],
       [ 7.59,  6.55,  8.67,  6.5 ,  8.74],
       [ 7.66,  8.85,  7.17,  8.61,  8.44]])

In [8]:
week_days == 'Tuesday'

array([False,  True, False, False, False], dtype=bool)

In [9]:
b=work_time[week_days == 'Tuesday'] #use an array as the filter to filter out the worktime on Tuesday--> 
                                # work_time[week_days == 'Tuesday']=work_time[[False,True,False,False,False]]
                                # Only return 2nd row because 2nd element is True
b

array([[ 7.59,  8.67,  9.58,  6.16,  7.99]])

> Note: if want to select column not row, simply use transpose: .T

In [10]:
b=work_time.T[week_days=='Tuesday']
b

array([[ 6.55,  8.67,  6.31,  6.55,  8.85]])

> Boolean indexing will not link child with parent array, the change of child will **NOT** effect parent

In [11]:
b[:,0]=100
print (b)
print (work_time)

[[ 100.      8.67    6.31    6.55    8.85]]
[[ 7.88  6.55  6.53  8.73  6.73]
 [ 7.59  8.67  9.58  6.16  7.99]
 [ 9.85  6.31  8.17  9.92  6.59]
 [ 7.59  6.55  8.67  6.5   8.74]
 [ 7.66  8.85  7.17  8.61  8.44]]


In [12]:
c=b[:,1:3]
c[:,0]=100
print (b)
print (work_time)

[[ 100.    100.      6.31    6.55    8.85]]
[[ 7.88  6.55  6.53  8.73  6.73]
 [ 7.59  8.67  9.58  6.16  7.99]
 [ 9.85  6.31  8.17  9.92  6.59]
 [ 7.59  6.55  8.67  6.5   8.74]
 [ 7.66  8.85  7.17  8.61  8.44]]
