# Important tools
numpy, scipy-- numerical calculation, matrix calculation, scientific calculation

pandas-- borrow R data structure (data frame) for data analysis

sklearn--useful, ML tools. 前两周课程重点

keras, tensorflow-- for deeplearning, neuronetwork

# Numpy
numpy defines the fundation of python for matrix calculation

np.add(A,B)

np.subtract(A,B)

np.multiply(C,D) AKA C*D, element*element in corresponding position. if A=3x1 mat, B=1x3 mat, then copy paste row or column, make A=3x3, and B=3x3, and then A*B 对应元素对应位置相乘


np.matmul(C,D) AKA C@D, vector by vector(Dot product) or matrix by matrix , e.g. (3x1 vec)by(3x1 vec) OR (2x3 mat) by (3x4 mat)

np.dot(C,D) NOTE: compared to matmul: 1-D array (nx1 vector or nx1/1xn mat) AND 2-D arrary (mxn mat) they are the same; ONLY for higher dimension array (e.g. mxnxq matrix), they are different,but 几乎不用高阶array!!!!!! 


重点看看 np.dot 和 np.matmul的区别

1.都是矩阵乘法

2.np.matmul中，禁止矩阵与标量的乘法

3.np.matmul中，在矢量乘矢量的内积运算中，matmul与dot没有差别

4.np.matmul中，多维的矩阵，将前n-2维视为后2维的元素后，进行乘法操作


In [1]:
import numpy as np
A=np.array([1,2,3])
B=np.array([4,3,0])
print ('A+B',np.add(A,B))
print ('A-B=',np.subtract(A,B))
print ('np.multiply(A,B)=',np.multiply(A,B))
print ('A*B=',A*B)

A+B [5 5 3]
A-B= [-3 -1  3]
np.multiply(A,B)= [4 6 0]
A*B= [4 6 0]


In [2]:
# for 1-D array (n*1 vector or n*1/1*n mat), matmul and dot are the same!!!

t1 = np.array([1,2,3])
t3 = np.array([1,2,3])
t2 = np.array([[1],
               [2],
               [3]])
#vector dot product with vector
print(np.dot(t1,t3))
print(np.matmul(t1,t3))

#matrix multiply by matrix
print(np.dot(t1,t2))
print(np.matmul(t1,t2))

print (t3.shape)
print (t1.shape)
print (t2.shape)

14
14
[14]
[14]
(3,)
(3,)
(3, 1)


In [4]:
#for 2-D array(m*n mat), malmul and dot are the same!!!

#C.shape=(2,3)->2*3 matrix; (2-D array)
C=np.array([[1,2,3],
           [1,1,1]])
#D.shape=(3,4)->3*4 matrix; (2-D array)
D=np.array([[4,3,9,9],
           [1,1,2,2],
           [4,2,1,1]])
print ('np.dot(C,D)=',np.dot(C,D))
print ('np.matmul(C,D)=', np.matmul(C,D))
print ('C@D=',C@D)

np.dot(C,D)= [[18 11 16 16]
 [ 9  6 12 12]]
np.matmul(C,D)= [[18 11 16 16]
 [ 9  6 12 12]]
C@D= [[18 11 16 16]
 [ 9  6 12 12]]


In [7]:
#Higher dimension array (3-D or above)(e.g. mxnxq matrix), matmul and dot are DIFFERENT

m_3_4_2 = np.array([
                             [[2,3],
                              [11,9],
                              [32,21],
                              [28,17]],
    
                             [[2,3],
                              [1,9],
                              [3,21],
                              [28,7]],
    
                             [[2,3],
                              [1,9],
                              [3,21],
                              [28,7]]
                            ])   #3-D array

m_4_4 = np.array([
                       [1,2,3,4],
                       [3,2,1,4],
                       [5,4,6,7],
                       [11,12,13,14]
                      ])   #2-D array


print('4x4*3x4x2 dot:\n {}\n'.format(np.dot(m_4_4,m_3_4_2))),print('dot 结果的维度    =',np.dot(m_4_4,m_3_4_2).shape)
print (' ')
print('4x4*3x4x2 matmul:\n {}\n'.format(np.matmul(m_4_4,m_3_4_2))),print('matmul 结果的维度 =',np.matmul(m_4_4,m_3_4_2).shape)

4x4*3x4x2 dot:
 [[[232 152]
  [125 112]
  [125 112]]

 [[172 116]
  [123  76]
  [123  76]]

 [[442 296]
  [228 226]
  [228 226]]

 [[962 652]
  [465 512]
  [465 512]]]

dot 结果的维度    = (4, 3, 2)
 
4x4*3x4x2 matmul:
 [[[232 152]
  [172 116]
  [442 296]
  [962 652]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]]

matmul 结果的维度 = (3, 4, 2)


(None, None)

# Sklearn

In [8]:
import sklearn

In [9]:
from sklearn import datasets
from sklearn.metrics import auc
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso