In [3]:
import numpy as np

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.exp(a)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [16]:
np.sqrt(a)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [17]:
b = np.random.randn(10)
b

array([-1.34050998, -0.72633561,  1.80934142,  0.0336691 , -1.75624725,
       -0.30284361, -1.90719424,  0.79378335,  0.56305977,  0.60218786])

In [18]:
c = np.random.randn(10).reshape(2,5)
c

array([[ 0.06789954,  1.46853961,  1.47266293, -1.24858916,  0.65869449],
       [ 0.81039602, -0.5017696 , -2.4088228 , -1.00251073,  0.70608127]])

In [19]:
np.shape(b)

(10,)

In [20]:
np.shape(a)

(10,)

In [22]:
# Binary Functions
np.add(a,b)

array([-1.34050998,  0.27366439,  3.80934142,  3.0336691 ,  2.24375275,
        4.69715639,  4.09280576,  7.79378335,  8.56305977,  9.60218786])